{
    "openapi": "3.0.0",
    "info": {
        "title": "Template - Typescript / Prisma / PostgreSQL",
        "description": "This is an Template for Node.js Project",
        "version": "1.0.0",
        "contact": {
            "email": "peixoto.pauloeduardo@gmail.com"
        }
    },
    "paths": {
        "/users": {
            "post": {
                "tags": [
                    "User"
                ],
                "summary": "Create a User.",
                "description": "Register at user on App.",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#definitions/CreateUser"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "User Created",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#definitions/UserCreated"
                                }
                            }
                        }
                    },
                    "422": {
                        "description": "Invalid Parameters",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#definitions/CreateUserInvalidParameters"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#definitions/ErrorServer"
                                }
                            }
                        }
                    }
                }
            },
            "get": {
                "tags": [
                    "User"
                ],
                "summary": "Find all Users.",
                "description": "List Users Registered at App.",
                "responses": {
                    "200": {
                        "description": "List Users",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#definitions/ListUsers"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#definitions/ErrorServer"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/users/email/{email}": {
            "get": {
                "tags": [
                    "User"
                ],
                "summary": "Find an User by email address",
                "description": "Show an User by email address",
                "parameters": [
                    {
                        "name": "email",
                        "in": "path",
                        "description": "Email Address",
                        "required": true,
                        "schema": {
                            "$ref": "#definitions/Email"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Show an User",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#definitions/ShowUser"
                                }
                            }
                        }
                    },
                    "403": {
                        "description": "User not found",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#definitions/UserNotFound"
                                }
                            }
                        }
                    },
                    "422": {
                        "description": "Internal server error.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#definitions/InvalidParameters"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#definitions/ErrorServer"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/users/username/{username}": {
            "get": {
                "tags": [
                    "User"
                ],
                "summary": "Find an User by username",
                "description": "Show an User by username",
                "parameters": [
                    {
                        "name": "username",
                        "in": "path",
                        "description": "Username",
                        "required": true,
                        "schema": {
                            "$ref": "#definitions/Username"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Show an User",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#definitions/ShowUser"
                                }
                            }
                        }
                    },
                    "403": {
                        "description": "User not found",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#definitions/UserNotFound"
                                }
                            }
                        }
                    },
                    "422": {
                        "description": "Internal server error.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#definitions/InvalidParameters"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#definitions/ErrorServer"
                                }
                            }
                        }
                    }
                }
            }
        },
        "users/id/{id}": {
            "get": {
                "tags": [
                    "User"
                ],
                "summary": "Find an User by id",
                "description": "Show an User by id",
                "parameters": [
                    {
                        "name": "username",
                        "in": "path",
                        "description": "Id",
                        "required": true,
                        "schema": {
                            "$ref": "#definitions/Id"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Show an User by Id",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#definitions/ShowUserById"
                                }
                            }
                        }
                    },
                    "403": {
                        "description": "User not found",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#definitions/UserNotFound"
                                }
                            }
                        }
                    },
                    "422": {
                        "description": "Internal server error.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#definitions/InvalidParameters"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#definitions/ErrorServer"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/posts": {
            "post": {
                "tags": [
                    "Post"
                ],
                "summary": "Create a Post.",
                "description": "Register an post at App.",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#definitions/CreatePost"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Post Created",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#definitions/PostCreated"
                                }
                            }
                        }
                    },
                    "422": {
                        "description": "Invalid Parameters",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#definitions/CreatePostInvalidParameters"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#definitions/ErrorServer"
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "Email": {
            "type": "string",
            "example": "usertest@email.com"
        },
        "Id": {
            "type": "string",
            "example": "a78b-547as-tr632x-us3r"
        },
        "Username": {
            "type": "string",
            "example": "usertest"
        },
        "CreateUser": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            },
            "example": {
                "name": "Fulano",
                "username": "fulano",
                "email": "fulano@email.com",
                "password": "123456"
            }
        },
        "UserCreated": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "user": {
                    "type": "object",
                    "properties": {
                        "id": {
                            "type": "string"
                        },
                        "username": {
                            "type": "string"
                        },
                        "email": {
                            "type": "string"
                        }
                    }
                }
            },
            "example": {
                "message": "User registered",
                "user": {
                    "id": "fc210d61-c64d-4067-af18-e49ad471d9d0",
                    "username": "fulano",
                    "email": "fulano@email.com"
                }
            }
        },
        "ListUsers": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    },
                    "username": {
                        "type": "string"
                    }
                }
            },
            "example": [
                {
                    "id": "fc210d61-c64d-4067-af18-e49ad471d9d0",
                    "name": "Fulano",
                    "username": "fulano"
                },
                {
                    "id": "d6c7bbf6-f3a5-4aec-8a1e-e018acc8cc4f",
                    "name": "User Controller",
                    "username": "user-controller"
                }
            ]
        },
        "ShowUser": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "user": {
                    "type": "object",
                    "properties": {
                        "id": {
                            "type": "string"
                        },
                        "username": {
                            "type": "string"
                        },
                        "email": {
                            "type": "string"
                        }
                    }
                }
            },
            "example": {
                "message": "User found!",
                "user": {
                    "id": "fc210d61-c64d-4067-af18-e49ad471d9d0",
                    "username": "fulano",
                    "email": "fulano@email.com"
                }
            }
        },
        "ShowUserById": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            },
            "example": {
                "id": "8ab08780-9174-4a5e-a0d7-7f45d15a87f3",
                "username": "usertest"
            }
        },
        "UserNotFound": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            },
            "example": {
                "message": "User not found!"
            }
        },
        "CreatePost": {
            "type": "object",
            "properties": {
                "title": {
                    "type": "string"
                },
                "author_id": {
                    "type": "string"
                }
            },
            "example": {
                "title": "Sample Post Two",
                "author_id": "8ab08780-9174-4a5e-a0d7-7f45d15a87f3"
            }
        },
        "PostCreated": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "post": {
                    "type": "object",
                    "properties": {
                        "id": {
                            "type": "string"
                        },
                        "title": {
                            "type": "string"
                        },
                        "author": {
                            "type": "string"
                        }
                    }
                }
            },
            "example": {
                "message": "Post registered",
                "post": {
                    "id": "81a16766-95e5-4b49-9fd8-461a73f242ce",
                    "title": "81a16766-95e5-4b49-9fd8-461a73f242ce",
                    "author": "usertest"
                }
            }
        },
        "ErrorServer": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            },
            "example": {
                "status": "error",
                "message": "Internal server error - { description_error }"
            }
        },
        "InvalidParameters": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            },
            "example": {
                "mesage": "Invalid Parameters"
            }
        },
        "InvalidEmail": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            },
            "example": {
                "mesage": "Invalid Email"
            }
        },
        "InvalidPassword": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            },
            "example": {
                "mesage": "Invalid Password"
            }
        },
        "InvalidName": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            },
            "example": {
                "mesage": "Invalid Name"
            }
        },
        "InvalidUsername": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            },
            "example": {
                "mesage": "Invalid Username"
            }
        },
        "InvalidTitle": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            },
            "example": {
                "mesage": "Invalid Title"
            }
        },
        "InvalidAuthorId": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            },
            "example": {
                "mesage": "Invalid Author ID"
            }
        },
        "CreateUserInvalidParameters": {
            "type": "array",
            "items": {
                "type": "object",
                "oneOf": [
                    {
                        "$ref": "#definitions/InvalidName"
                    },
                    {
                        "$ref": "#definitions/InvalidUsername"
                    },
                    {
                        "$ref": "#definitions/InvalidEmail"
                    },
                    {
                        "$ref": "#definitions/InvalidPassword"
                    },
                    {
                        "$ref": "#definitions/InvalidParameters"
                    }
                ]
            }
        },
        "CreatePostInvalidParameters": {
            "type": "array",
            "items": {
                "type": "object",
                "oneOf": [
                    {
                        "$ref": "#definitions/InvalidTitle"
                    },
                    {
                        "$ref": "#definitions/InvalidAuthorId"
                    },
                    {
                        "$ref": "#definitions/InvalidParameters"
                    }
                ]
            }
        }
    }
}